table_schema: dict[str, str] = {
    "id": "INTEGER PRIMARY KEY AUTOINCREMENT",
    "ts_received": "TIMESTAMP NOT NULL",
    "price_1": "REAL NOT NULL",
    "volume_1": "REAL NOT NULL",
    "price_2": "REAL NOT NULL",
    "volume_2": "REAL NOT NULL",
    "price_3": "REAL NOT NULL",
    "volume_3": "REAL NOT NULL",
    "price_4": "REAL NOT NULL",
    "volume_4": "REAL NOT NULL",
    "price_5": "REAL NOT NULL",
    "volume_5": "REAL NOT NULL",
    "price_6": "REAL NOT NULL",
    "volume_6": "REAL NOT NULL",
    "price_7": "REAL NOT NULL",
    "volume_7": "REAL NOT NULL",
    "price_8": "REAL NOT NULL",
    "volume_8": "REAL NOT NULL",
    "price_9": "REAL NOT NULL",
    "volume_9": "REAL NOT NULL",
    "price_10": "REAL NOT NULL",
    "volume_10": "REAL NOT NULL"
}